name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Pharmabag Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Project to EC2
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --exclude=".git" --exclude="node_modules" --exclude=".next"
          path: ./
          remote_path: /home/ubuntu/project-pharmabag-web/pharmabag-web/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            cd /home/ubuntu/project-pharmabag-web

            echo "Building and deploying frontend containers..."

            docker compose up -d --build --remove-orphans

            echo "Cleaning up unused Docker images..."

            docker image prune -f

            echo "✅ Pharmabag Web deployed successfully."
